#!/bin/bash

javac -target 1.8 JLex/Main.java
java JLex.Main Calculator.lex
mv -f Calculator.lex.java Yylex.java
java -cp JavaCup java_cup.Main Calculator.cup
javac -cp .:JavaCup -d . parser.java sym.java Yylex.java
java -cp .:JavaCup Calculator.parser
