
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 31 09:16:18 SGT 2016
//----------------------------------------------------

package Calculator;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int RSHIFT = 9;
  public static final int POW = 10;
  public static final int DIVIDE = 7;
  public static final int LSHIFT = 8;
  public static final int NUMBER = 13;
  public static final int MOD = 6;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int error = 1;
  public static final int RPAREN = 12;
  public static final int TIMES = 5;
  public static final int LPAREN = 11;
}

