
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 04 00:25:00 SGT 2016
//----------------------------------------------------

package Calculator;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 6;
  public static final int MOD = 7;
  public static final int LONG = 25;
  public static final int AND = 13;
  public static final int SIN = 19;
  public static final int PLUS = 3;
  public static final int OR = 15;
  public static final int RPAREN = 12;
  public static final int COT = 22;
  public static final int COS = 20;
  public static final int SEMI = 2;
  public static final int NOT = 5;
  public static final int RSHIFT = 10;
  public static final int SQRT = 17;
  public static final int POW = 16;
  public static final int LPAREN = 11;
  public static final int LOG = 18;
  public static final int LSHIFT = 9;
  public static final int EOF = 0;
  public static final int DIVIDE = 8;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int XOR = 14;
  public static final int CSC = 24;
  public static final int TAN = 21;
  public static final int SEC = 23;
  public static final int DOUBLE = 26;
}

