
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 31 22:14:30 SGT 2016
//----------------------------------------------------

package Calculator;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 6;
  public static final int MOD = 7;
  public static final int LONG = 17;
  public static final int AND = 11;
  public static final int PLUS = 3;
  public static final int OR = 13;
  public static final int RPAREN = 16;
  public static final int SEMI = 2;
  public static final int NOT = 5;
  public static final int RSHIFT = 10;
  public static final int POW = 14;
  public static final int LPAREN = 15;
  public static final int LSHIFT = 9;
  public static final int EOF = 0;
  public static final int DIVIDE = 8;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int XOR = 12;
}

